// ─── Egyptian Restaurant Data ─────────────────────────────────────────────

export const CATEGORIES = [
  { id: 'all',        name: 'الكل',       icon: '🍽️' },
  { id: 'grills',     name: 'مشويات',     icon: '🔥' },
  { id: 'koshary',    name: 'كشري',       icon: '🥣' },
  { id: 'sandwiches', name: 'سندويشات',   icon: '🥪' },
  { id: 'meals',      name: 'وجبات',      icon: '🍱' },
  { id: 'sides',      name: 'إضافات',     icon: '🥗' },
  { id: 'drinks',     name: 'مشروبات',    icon: '🥤' },
  { id: 'desserts',   name: 'حلويات',     icon: '🍮' },
]

export const PRODUCTS = [
  {
    id: 1,
    name: 'مشاوي الحبايب المشكلة',
    category: 'grills',
    price: 180,
    description: 'تشكيلة فاخرة من أجود أنواع اللحوم المشوية على الفحم الطبيعي — كباب، كفتة، فيليه دجاج، وكوارع',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&q=80',
    badge: 'الأكثر طلباً',
    badgeColor: 'gold',
    rating: 4.9,
    reviews: 342,
    isPopular: true,
    inStock: true,
    stockQty: 50,
    calories: 950,
    prepTime: '25 دقيقة',
  },
  {
    id: 2,
    name: 'كشري الحبايب الكبير',
    category: 'koshary',
    price: 35,
    description: 'كشري مصري أصيل بالأرز والمكرونة والعدس والبصل المقلي الذهبي وصوص الطماطم الحار',
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&q=80',
    badge: 'الأشهر',
    badgeColor: 'red',
    rating: 4.9,
    reviews: 890,
    isPopular: true,
    inStock: true,
    stockQty: 100,
    calories: 620,
    prepTime: '5 دقائق',
  },
  {
    id: 3,
    name: 'حمام محشي بالأرز',
    category: 'grills',
    price: 120,
    description: 'حمام مصري طازج محشو بالأرز الأبيض والبهارات ومطهو بالسمن البلدي',
    image: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=600&q=80',
    badge: null,
    rating: 4.8,
    reviews: 215,
    isPopular: true,
    inStock: true,
    stockQty: 20,
    calories: 480,
    prepTime: '30 دقيقة',
  },
  {
    id: 4,
    name: 'طاجن لحمة بالخضار',
    category: 'meals',
    price: 160,
    description: 'طاجن مصري تقليدي باللحمة الضاني والخضار الطازجة والصوص الغني بالتوابل الشرقية',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&q=80',
    badge: 'بيتي',
    badgeColor: 'gold',
    rating: 4.9,
    reviews: 456,
    isPopular: true,
    inStock: true,
    stockQty: 30,
    calories: 750,
    prepTime: '35 دقيقة',
  },
  {
    id: 5,
    name: 'سندويش كباب حار',
    category: 'sandwiches',
    price: 45,
    description: 'عيش بلدي طازج بالكباب المشوي والطحينة والبقدونس والبصل المخلل',
    image: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=600&q=80',
    badge: null,
    rating: 4.7,
    reviews: 278,
    isPopular: false,
    inStock: true,
    stockQty: 60,
    calories: 420,
    prepTime: '10 دقيقة',
  },
  {
    id: 6,
    name: 'سندويش فلافل بلدي',
    category: 'sandwiches',
    price: 20,
    description: 'فلافل مقرمشة محضرة من الفول والحمص مع الطحينة والخضروات الطازجة في عيش بلدي',
    image: 'https://images.unsplash.com/photo-1593001872095-7d5b3868fb1d?w=600&q=80',
    badge: null,
    rating: 4.6,
    reviews: 634,
    isPopular: false,
    inStock: true,
    stockQty: 80,
    calories: 380,
    prepTime: '8 دقائق',
  },
  {
    id: 7,
    name: 'بطاطس مشوية بالتوابل',
    category: 'sides',
    price: 30,
    description: 'بطاطس كانتري مشوية بتوابل البهارات الشرقية والكمون والكزبرة',
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=600&q=80',
    badge: null,
    rating: 4.5,
    reviews: 189,
    isPopular: false,
    inStock: true,
    stockQty: 70,
    calories: 320,
    prepTime: '12 دقيقة',
  },
  {
    id: 8,
    name: 'عصير قصب طازج',
    category: 'drinks',
    price: 20,
    description: 'عصير قصب السكر الطازج المعصور أمامك فوراً، منعش وطبيعي 100%',
    image: 'https://images.unsplash.com/photo-1546173159-315724a31696?w=600&q=80',
    badge: null,
    rating: 4.8,
    reviews: 967,
    isPopular: false,
    inStock: true,
    stockQty: 200,
    calories: 140,
    prepTime: '3 دقائق',
  },
  {
    id: 9,
    name: 'أم علي بالمكسرات',
    category: 'desserts',
    price: 45,
    description: 'حلوى أم علي المصرية الأصيلة بالعجين الهش والمكسرات والزبيب والقشطة على الفرن',
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600&q=80',
    badge: 'مميز',
    badgeColor: 'gold',
    rating: 4.9,
    reviews: 512,
    isPopular: true,
    inStock: true,
    stockQty: 25,
    calories: 480,
    prepTime: '15 دقيقة',
  },
  {
    id: 10,
    name: 'كباب لحمة وكفتة',
    category: 'grills',
    price: 140,
    description: 'تشكيلة كباب لحم ضاني وكفتة الدجاج المشوية على الفحم مع صوص الثوم والخضار',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=600&q=80',
    badge: null,
    rating: 4.8,
    reviews: 298,
    isPopular: false,
    inStock: true,
    stockQty: 40,
    calories: 680,
    prepTime: '20 دقيقة',
  },
  {
    id: 11,
    name: 'سلطة بلدي طازجة',
    category: 'sides',
    price: 25,
    description: 'طماطم وخيار وبصل وفلفل أخضر طازج مع زيت الزيتون وعصير الليمون والكمون',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80',
    badge: null,
    rating: 4.6,
    reviews: 176,
    isPopular: false,
    inStock: true,
    stockQty: 60,
    calories: 120,
    prepTime: '5 دقائق',
  },
  {
    id: 12,
    name: 'تمر هندي وعرق سوس',
    category: 'drinks',
    price: 18,
    description: 'مشروبات رمضانية وشعبية — تمر هندي بارد أو عرق سوس طازج مُحلّى بالسكر',
    image: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=600&q=80',
    badge: null,
    rating: 4.7,
    reviews: 345,
    isPopular: false,
    inStock: true,
    stockQty: 150,
    calories: 160,
    prepTime: '2 دقائق',
  },
  {
    id: 13,
    name: 'وجبة الأسرة الكبيرة',
    category: 'meals',
    price: 380,
    description: 'وجبة عائلية تكفي 5-6 أشخاص: مشاوي مشكلة + أرز أبيض + خبز بلدي + سلطات + مشروبات',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&q=80',
    badge: 'عرض خاص',
    badgeColor: 'gold',
    rating: 5.0,
    reviews: 156,
    isPopular: true,
    inStock: true,
    stockQty: 10,
    calories: 3800,
    prepTime: '40 دقيقة',
  },
]

export const OFFERS = [
  {
    id: 1,
    title: 'وجبة الاثنين بنص التمن',
    description: 'أي وجبة فردية بخصم 50% كل يوم اثنين من 2م حتى 5م',
    discount: '50%',
    image: 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=600&q=80',
    color: 'from-red-900 to-red-700',
    validUntil: '2025-12-31',
  },
  {
    id: 2,
    title: 'وجبة الأسرة',
    description: 'مشاوي مشكلة لـ 6 أشخاص + مشروبات مجانية',
    discount: '30%',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&q=80',
    color: 'from-amber-900 to-amber-700',
    validUntil: '2025-12-31',
  },
  {
    id: 3,
    title: 'كشري + مشروب',
    description: 'طبق كشري كبير + عصير قصب بـ 40 جنيه بس',
    discount: '20%',
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&q=80',
    color: 'from-green-900 to-green-700',
    validUntil: '2025-12-31',
  },
]

export const REVIEWS = [
  {
    id: 1,
    name: 'أحمد الجندي',
    avatar: 'أج',
    rating: 5,
    text: 'أحسن كشري أكلته في حياتي! صحيح كده زي بيت مامتي. والمشاوي مش كلام، الفحم ريحته بتعمل جوع من بره.',
    date: 'منذ يومين',
    verified: true,
  },
  {
    id: 2,
    name: 'منة الله سمير',
    avatar: 'من',
    rating: 5,
    text: 'وجبة الأسرة استلمتها سخنة وكاملة. الحمام المحشي ده مش بيتلاقى بالسهل. شكراً الحبايب!',
    date: 'منذ 4 أيام',
    verified: true,
  },
  {
    id: 3,
    name: 'كريم عبدالله',
    avatar: 'كع',
    rating: 5,
    text: 'من زمان وأنا بدور على طعم البيت المصري الحقيقي. لقيته هنا. الطاجن واللحمة ذابت في بعض.',
    date: 'منذ أسبوع',
    verified: true,
  },
  {
    id: 4,
    name: 'ريم محمود',
    avatar: 'رم',
    rating: 4,
    text: 'التوصيل جه في الوقت وكل حاجة زي ما طلبتها. أم علي بالمكسرات ده بجد يستاهل.',
    date: 'منذ أسبوعين',
    verified: false,
  },
]

export const STATS = [
  { value: '12K+', label: 'طلب شهرياً' },
  { value: '8',    label: 'سنوات خبرة' },
  { value: '60+',  label: 'صنف في المنيو' },
  { value: '4.9',  label: 'تقييم العملاء' },
]

export const WHY_US = [
  { icon: '🔥', title: 'فحم طبيعي', description: 'مشويات على الفحم البلدي الطبيعي بدون أي مواد حافظة' },
  { icon: '⚡', title: 'توصيل سريع', description: 'نوصلك في أقل من 45 دقيقة أو الطلب مجاناً' },
  { icon: '👨‍🍳', title: 'طهاة بيتيين', description: 'طهاة متخصصون في الأكل المصري البيتي الأصيل' },
  { icon: '💰', title: 'أسعار الناس', description: 'جودة عالية بأسعار تناسب كل الأسر المصرية' },
]

// ─── Default Delivery Zones ──────────────────────────────────────────────
export const DEFAULT_DELIVERY_ZONES = [
  { id: 'zone_1', name: 'داخل البلد',      fee: 10,  estimatedTime: '20-30 دقيقة' },
  { id: 'zone_2', name: 'القرى المجاورة',  fee: 20,  estimatedTime: '30-45 دقيقة' },
  { id: 'zone_3', name: 'خارج المركز',     fee: 35,  estimatedTime: '45-60 دقيقة' },
]
